### PR TITLE
Fixes "Main page caching doesn't work properly"

### PR DESCRIPTION
**Pull request by SunPj**
Last-Modified HTTP header of assets contained in jar is wrong

See https://github.com/playframework/playframework/issues/10572

### CODE REVIEW

**Comment by mkurz** [comment]
This makes sense.
@SunPj do you make actual use of this repo here actually?

**Comment by SunPj** [comment]
@mkurz Yes I use it

**Comment by mkurz** [comment]
@SunPj are there any other problems with this seed project? Would you be interested in becoming a maintainer of it? So you can merge pull requests, push commits etc. to keep this seed project up to date, also of course you can enhance it.
What do you think?

**Comment by mkurz** [comment]
@SunPj I added you as maintainer to this repo right now, you need to accept the inviation.

**Comment by SunPj** [comment]
Thanks @mkurz I have just accepted your invitation

**Pull request merged**
